### ISSUE TITLE
Expected use of cmw and CF in IANA section could be more clear

### ISSUE THREAD

**Issue by nedmsmith** [ietf-rats-wg/draft-ietf-rats-msg-wrap#123]
Section 10.3 defines the CBOR tag `CPA765` and section 6. defines the expected content as `CMW`. 

Section 10.6 requests TBD1 and TBD2 from CF registry. Section 3.2 defines $cbor-tag socket and uses example `tn` and `$fmt` inputs to the macro. But it doesn't describe if the macro should be used for the TBD1 input.  There is an example that defines $cbor-tag as `cbor-tag<1668576818, any>`. But it isn't clear if 1668576818 is the intended TN result from TBD1 or if the intended $fmt is `any`.  In other words, is the following macro definition intended?
```
; 1668576818 = tn(TBD1)
$cbor-tag /= cbor-tag<1668576818, any>
; or possibly
$cbor-tag /= cbor-tag<1668576818, cmw>
```
The various media-type / content-format names use `cmw` (e.g., `cmw+cbor`, `cmw+json`), but there isn't text that explicitly associates the I-D use of "CMW" with the cddl `cmw`.  The top level `cmw` isn't discussed in the normative part of the I-D. For example, it would be helpful if the following cddl was described in section 3.
```
cmw = json-CMW / cbor-CMW

json-CMW = json-record / json-collection
cbor-CMW = cbor-record / cbor-collection / $cbor-tag
```
with text that equates CMW with `cmw`.

**Comment by thomas-fossati** [comment]
Since in -10 we have removed the plug-in for EAT submods, this issue seems OBE.

@nedmsmith could you confirm?  (If so, please close this.)

**Comment by nedmsmith** [comment]
> Since in -10 we have removed the plug-in for EAT submods, this issue seems OBE.

No. The issue is `cmw` isn't defined normatively. 
Section 3 refers to appendix A, which contains `cmw`, but appendices are not normative.

Section 3 also incorrectly positions that there are 2 CMW types defined in the draft, but there are 3 since it defines an ASN.1 form. There is a top level definition of CMW for the ASN.1 form
```
CMW ::= CHOICE {
    json UTF8String,
    cbor OCTET STRING
}
```
But not the CDDL form.

The document readability is diminished by lax use of "CMW" as both an acronym for "Conceptual Message Wrapper", a normative ASN.1 expression and a normative CBOR/JSON expression (at least in part) in `json-CMW` and `cbor-CMW`. None of the other CDDL uses upper case, so it is a strange break in convention.

**Comment by thomas-fossati** [comment]
> > Since in -10 we have removed the plug-in for EAT submods, this issue seems OBE.
> 
> No. The issue is `cmw` isn't defined normatively. Section 3 refers to appendix A, which contains `cmw`

We could add the top level rules into Section 3:

```
start = cmw

cmw = json-CMW / cbor-CMW

json-CMW = json-record / json-collection
cbor-CMW = cbor-record / cbor-collection / $cbor-tag
```

Alternatively, we could move the CDDL to a normal section in the `--- middle` of the document.

> [...] appendices are not normative.

I am not sure that's the case.  This is @henkbirkholz's mantra ;-) but I have at least one example of a normative appendix in mind.

> Section 3 also incorrectly positions that there are 2 CMW types defined in the draft, but there are 3 since it defines an ASN.1 form. There is a top level definition of CMW for the ASN.1 form
> 
> ```
> CMW ::= CHOICE {
>     json UTF8String,
>     cbor OCTET STRING
> }
> ```

I wonder whether this can be considered a distinct definition though.  I see it just as an ASN.1 stash for something that's defined elsewhere.

> The document readability is diminished by lax use of "CMW" as both an acronym for "Conceptual Message Wrapper", a normative ASN.1 expression and a normative CBOR/JSON expression (at least in part) in `json-CMW` and `cbor-CMW`. None of the other CDDL uses upper case, so it is a strange break in convention.

I am not adverse to change.  I only lack a bit of fantasy and motivation in this specific case :-) Do you have a suggestion?

**Comment by nedmsmith** [comment]
>We could add the top level rules into Section 3:

This is my preference. Section 3 should be re-titled to "Conceptual Message Wrapper" since this section is both about the type and the encoding.

A new section 3.1 should be created that describes the top-level construction of "cmw".  The document flows better if it describes the thing from top to bottom rather than the other way around. Mathematicians might prefer the other way around, but everybody else prefers top down (IMHO).

The new section 3.1 could point out that the ASN.1/der encoding is another form of `cmw` as in:
```
cmw = json-CMW / cbor-CMW / CMW
```
But the CDDL bridge to ASN.1 isn't there yet. But the wording should make it clear that the above CDDL example is what is intended.

>I am not sure that's the case.

If in doubt put it in the main body of the spec.

>I wonder whether this can be considered a distinct definition though. I see it just as an ASN.1 stash for something that's defined elsewhere.

The stash is just a reference back to the json-CMW or cbor-CMW, but the top level definition implies all of the above forms are defined. The CDDL could have used an extensible type form to make it clear there could be others defined down the road (as these are the "basic" definitions).
```
cmw-type /= cbor-CMW
cmw-type /= json-CMW
cmw-type /= der-CMW ; where der-CMW is defined by the ASN.1 definition of `CMW`
```
>Do you have a suggestion?

What about:
```
cmw = json-cmw / cbor-cmw
json-cmw = json-record / json-collection
cbor-cmw = cbor-record / cbor-collection / $cbor-tag
```
or
```
cmw = cmw-type
cmw-type /= json-cmw
cmw-type /= cbor-cmw
```

**Comment by thomas-fossati** [comment]
> > We could add the top level rules into Section 3:
> 
> This is my preference. Section 3 should be re-titled to "Conceptual Message Wrapper" since this section is both about the type and the encoding.
> 
> A new section 3.1 should be created that describes the top-level construction of "cmw". The document flows better if it describes the thing from top to bottom rather than the other way around.

Noted.

> Mathematicians might prefer the other way around, but everybody else prefers top down (IMHO).

That must be it then :-)

> The new section 3.1 could point out that the ASN.1/der encoding is another form of `cmw` as in:
> 
> ```
> cmw = json-CMW / cbor-CMW / CMW
> ```
> 
> But the CDDL bridge to ASN.1 isn't there yet. But the wording should make it clear that the above CDDL example is what is intended.

Yes, that needs to be stated in natural language.

> > I am not sure that's the case.
> 
> If in doubt put it in the main body of the spec.

TBH, I don't know where this thing about default non-normative appendixes in RFCs comes from.
Henk is the first IETF person I know who's so adamant about that :-)
 
> > I wonder whether this can be considered a distinct definition though. I see it just as an ASN.1 stash for something that's defined elsewhere.
> 
> The stash is just a reference back to the json-CMW or cbor-CMW, but the top level definition implies all of the above forms are defined. The CDDL could have used an extensible type form to make it clear there could be others defined down the road (as these are the "basic" definitions).
> ```
> cmw-type /= cbor-CMW
> cmw-type /= json-CMW
> cmw-type /= der-CMW ; where der-CMW is defined by the ASN.1 definition of `CMW`
> ```

CDDL is CBOR/JSON only, it can't plug into another language.  Well, it can pull in ABNF, but not ASN.1 or other spec languages I am afraid.


>  > Do you have a suggestion?
> 
> What about:
> 
> ```
> cmw = json-cmw / cbor-cmw
> json-cmw = json-record / json-collection
> cbor-cmw = cbor-record / cbor-collection / $cbor-tag
> ```

WFM!
