### ISSUE TITLE
Consistent use of term "tag"

### ISSUE THREAD

**Issue by laurencelundblade** [ietf-rats-wg/draft-ietf-rats-msg-wrap#133]
* [x] 3.2 mentions "prepending a tag". I think this should be "tag number" since a "tag" is the number plus content.

* [x] The first sentence in 3.2 is hard for me to interpret too.

* [ ] The term "CMW CBOR Tag" may have double meaning, one in 3.2 and the other in 9.3.

* [x] I don't know what a '"native" CBOR type' is.

**Comment by thomas-fossati** [comment]
> The term "CMW CBOR Tag" may have double meaning, one in 3.2 and the other in 9.3.

The context should be sufficient to eliminate the potential ambiguity.
