### ISSUE TITLE
RFC 9277 has exceptions for bstr wrapping of TN() (I think)

### ISSUE THREAD

**Issue by laurencelundblade** [ietf-rats-wg/draft-ietf-rats-msg-wrap#135]
If I understand it, if the content of the TN tag is not a byte string, but rather tag 55799, 55800, or 55801, then byte string wrapping is side stepped.

That means the CDDL in the CMW document that forces the tag content to a byte string is wrong.

So 1668546930(55799(sensml-stuff-in-CBOR)) for sensml content.

I still kind of wonder about making the section on tags very small and simple so as to not draw attention to them as we prefer content/media types.

**Comment by thomas-fossati** [comment]
> If I understand it, if the content of the TN tag is not a byte string, but rather tag 55799, 55800, or 55801, then byte string wrapping is side stepped.

I think it's the other way around:

> _"Exceptionally, when used immediately as tag content of one of the tags 55799, 55800, or 55801, the tag content is as follows [...]"_

talks about the case where a TN-derived tag is the tag content of one of 55799-55801, e.g., 55800(1330664270(h'424F52')).

This is not how we plan to use TN.  (Actually, this is another solid good argument for avoiding any non-TN tag as the outer type indicator.)

**Comment by laurencelundblade** [comment]
Yes, you are right.
