### ISSUE TITLE
`s/cmw-array/cmw-record/g`

### ISSUE THREAD

**Issue by thomas-fossati** [ietf-rats-wg/draft-ietf-rats-msg-wrap#38]
We should change the `cmw-array` to `cmw-record` so people don’t get the wrong impression that cmw-array is an array of cmw.

A `cmw-collection` might be an appropriate name for an array of cmw.

(These points were originally raised by @nedmsmith)

**Comment by thomas-fossati** [comment]
@nedmsmith: checking if this is still needed?

**Comment by nedmsmith** [comment]
Now is the time to change it if we're going to. It's a nit. But technically both maps and records can be used to make arrays.
