### ISSUE TITLE
request an OID for embedding CMWs in certs

### ISSUE THREAD

**Issue by thomas-fossati** [ietf-rats-wg/draft-ietf-rats-msg-wrap#44]
Current work in TCG DICE and IETF "attested CSR" requires embedding CMWs in X.509 artefacts (certs and CSRs).

We should register the relevant OIDs with IANA.

**Comment by nedmsmith** [comment]
The TCG specification is publicly available here: https://trustedcomputinggroup.org/wp-content/uploads/DICE-Attestation-Architecture-Version-1.1-Revision-18_pub.pdf

**Comment by nedmsmith** [comment]
Given cmw I-D more recently included cmw-collection, would it make sense for it to also define an ASN.1 form and register an OID?

**Comment by thomas-fossati** [comment]
> The TCG specification is publicly available here: https://trustedcomputinggroup.org/wp-content/uploads/DICE-Attestation-Architecture-Version-1.1-Revision-18_pub.pdf

My bad! I missed this definition from DICE-AA:
```asn.1
tcg-dice-conceptual-message-wrapper OBJECT IDENTIFIER ::= {tcg-dice 9}
```

I guess it can be used as-is?

> Given cmw I-D more recently included cmw-collection, would it make sense for it to also define an ASN.1 form and register an OID?

OK, what's left is registering one OID for the collection, i.e.:

```asn.1
cmw-collection OBJECT IDENTIFIER ::= { TBD }

CMWCollection ::= OCTET STRING
```

@hannestschofenig @nedmsmith?

**Comment by nedmsmith** [comment]
LGTM
