### ISSUE TITLE
§3.4 (CMW collection) needs some TLC

### ISSUE THREAD

**Issue by thomas-fossati** [ietf-rats-wg/draft-ietf-rats-msg-wrap#46]
@henkbirkholz has the following comments regarding prose in §3.4:

* https://github.com/ietf-rats-wg/draft-ietf-rats-msg-wrap/pull/45#discussion_r1465003510
* https://github.com/ietf-rats-wg/draft-ietf-rats-msg-wrap/pull/45#discussion_r1465004847
* https://github.com/ietf-rats-wg/draft-ietf-rats-msg-wrap/pull/45/commits/8c5dcc304cd21a6c6672c3c2ca47fa70f315ee29#r1465272666

**Comment by henkbirkholz** [comment]
Seems we're going with merged #45? Everybody actually happy with that? (non-blocking)

**Comment by thomas-fossati** [comment]
> Seems we're going with merged #45? Everybody actually happy with that? (non-blocking)

Note that #45 has none of the editorial suggestions you provided in the review.

I guess you need to decide whether the current state of the section is acceptable or if you want to tweak it.

**Comment by thomas-fossati** [comment]
@henkbirkholz is this issue still valid?  Or can it be closed?

**Comment by thomas-fossati** [comment]
Hearing no shouting I will close.  @henkbirkholz, feel free to reopen if you think otherwise.
