### ISSUE TITLE
improve the ASN.1 definition of CMWCollection

### ISSUE THREAD

**Issue by thomas-fossati** [ietf-rats-wg/draft-ietf-rats-msg-wrap#49]
Discussion starting here:
* https://mailarchive.ietf.org/arch/msg/rats/eFBCC1JxC573SkDSp6yWZ4J_dyM/

We may want to define CMWCollection with finer granularity, e.g.:
```asn.1
CMWCollection ::= CHOICE {
    json UTF8String,
    cbor OCTET STRING,
}
```

**Comment by nedmsmith** [comment]
WFM
