### ISSUE TITLE
"Endorsement", rather than "Endorsements"

### ISSUE THREAD

**Issue by laurencelundblade** [ietf-rats-wg/draft-ietf-rats-msg-wrap#58]
In Table 2 in 7.4.2 shouldn't  it be "Endorsement"? It's just one endorsement per conceptual message, right?

Ref values is correct as plural. Evidence is fine too.

Attestation Results could be singular, but seems OK plural.

**Comment by henkbirkholz** [comment]
So there are never more than one Endorsements?

**Comment by nedmsmith** [comment]
> So there are never more than one Endorsements?

The plurality refers to Claims. A single conceptual message can have more than one Claim. Endorsements are not a special case. If you change all the entries in the table to include "Claims" the entries would be Reference Value Claims, Endorsement Claims, Evidence Claims, etc...

**Comment by laurencelundblade** [comment]
> So there are never more than one Endorsements?

Can a conceptual message contain more than one endorsement or not? Seems like it could go either way. If it can contain more than one, you'd need to make it an array (which is beyond the scope of this draft).

RATs architecture uses plurality for these terms, but could be discussing "messages" rather than a "message". https://www.rfc-editor.org/rfc/rfc9334.html#name-conceptual-messages

The plurality of "attestation results" and "reference values" is kind of ambiguous. It makes a lot of sense to have many references values in a conceptual message.

Not a big deal either way, but seemed worth cross-checking.

**Comment by laurencelundblade** [comment]
> > Can a conceptual message contain more than one endorsement or not? Seems like it could go either way. If it can contain more than one, you'd need to make it an array (which is beyond the scope of this draft).
> 
> Yes, it can. For example, a CoRIM payload potentially contains several endorsements (and reference values too.)

To go on a bit more. I think a reference value *set* is equivalent to an endorsement. A conceptual message might contain several reference value sets like it might contain multiple endorsements.

Or call it a reference value "bundle" or whatever you like.

**Comment by thomas-fossati** [comment]
> > > Can a conceptual message contain more than one endorsement or not? Seems like it could go either way. If it can contain more than one, you'd need to make it an array (which is beyond the scope of this draft).
> > 
> > 
> > Yes, it can. For example, a CoRIM payload potentially contains several endorsements (and reference values too.)
> 
> To go on a bit more. I think a reference value _set_ is equivalent to an endorsement. A conceptual message might contain several reference value sets like it might contain multiple endorsements.
> 
> Or call it a reference value "bundle" or whatever you like.

I'd rather not add new terminology.

`cm-ind` is a bit map, so one can signal the presence of multiple different conceptual messages within the same CMW.
