### ISSUE TITLE
two `cmw` definitions

### ISSUE THREAD

**Issue by nedmsmith** [ietf-rats-wg/draft-ietf-rats-msg-wrap#72]
I'm confused by cmw-start.cddl and cmw.cddl. Each has a definition for `cmw`.  frags.mk ignores cmw.cddl so possibly removal of cmw.cddl is needed? However, I prefer the convention that the "start" file contains only the start directive. This makes it easy to replace with a different start vector for debugging purposes. It would be better to put the cmw definition in cmw.cddl and include it in the frags.mk IMHO.

**Comment by thomas-fossati** [comment]
You are right.  I spotted the dead code while working on #71, which removes `cmw.cddl` for good.

**Comment by thomas-fossati** [comment]
> This has been addressed in #71. @nedmsmith could you confirm?

OK, I've got indirect confirmation by your closing of #73 😄
