### ISSUE TITLE
Pre-allocation to RATS Conceptual Message Wrapper Indicators" registry

### ISSUE THREAD

**Issue by nedmsmith** [ietf-rats-wg/draft-ietf-rats-msg-wrap#90]
IANA is not allowed to create a new registry and create pre-allocation entries. 

RFC 7120 allows for early allocations from existing registries (with chair and AD approval, or just AD approval if the document is AD-sponsored), but it doesn't permit the early creation of registries.

We are looking at how to make this work for a 7120bis (no text yet), which we'll be discussing with the IESG in Vancouver, but that's not very helpful at the moment. (Logistical issues include what to do with abandoned registries given that we prefer not to delete them, whether intended registration procedure should affect the early registration procedure, and how allocations from yet-to-be-approved documents should be carried over when the IESG approves the document that contains the registry.)

In the meantime, the two options available would probably be to 1) include any other drafts' registrations in the document that contains the registry, and use a "reference" field to refer to those other drafts, or 2) limit the registrations in the I-D version of the registry as desired, but have the WG maintain a living registry of some kind in a wiki or in github that can contain entries for other documents. In the latter case, it would be important to make sure that nobody can add entries to that living pre-registry once IANA creates the actual registry.

IANA expert also asked the CMW authors to add the following text to the IANA section, table 2, for this registry:
"4-255 | Unassigned".

**Comment by thomas-fossati** [comment]
In terms of new registries, we only create the ["CMW indicators"](https://www.ietf.org/archive/id/draft-ietf-rats-msg-wrap-04.html#section-8.4), which comes pre-populated with a bunch of reasonable codepoints already.

To cover the (remote?) risk of someone wanting to add further registration in the short term, I like the idea of handling a "provisional registry" page as a file under revision control in the msg-wrap repo.  People wanting to add their codepoints would make a PR changing that file (and the I-D).

**Comment by nedmsmith** [comment]
So, we should say no to IANA for using the provisional registry?

**Comment by thomas-fossati** [comment]
> So, we should say no to IANA for using the provisional registry?

yes, we can host the provisional registry ourselves and shut it down when IANA takes over.

**Comment by nedmsmith** [comment]
I withdrew the IANA request for CMW Indicators registry early allocation.

**Comment by thomas-fossati** [comment]
> I withdrew the IANA request for CMW Indicators registry early allocation.

Cool.  I'll take this as a yes to my question: https://github.com/ietf-rats-wg/draft-ietf-rats-msg-wrap/issues/90#issuecomment-2141676903 :-)
